### ISSUE TITLE
IANAL, but the MIT license might not (maybe?) be a great idea for a template

### ISSUE THREAD

**Issue by jakobrs** [nix-community/nur-packages-template#12]
**I am not a lawyer. This is not legal advice.**

See <https://logs.nix.samueldr.com/nixos/2020-04-04#1585980338-1585979107;>, from 5:45 to 6:05.

I would go more in-depth here, but **IANAL**, I'm being indirect to stay clear.

Once again, **I am not a lawyer**, please do not rely on the attempted information presented by me, cole-h, simpson, colemickens, or pjt_014 as if it were legal advice.

**Comment by Mic92** [comment]
We require every user to share their Nix expressions under MIT license anyway when they add it to NUR: https://github.com/nix-community/NUR/pull/204

**Comment by jakobrs** [comment]
That's a valid point. The template itself being MIT-licensed, however, means that any repositories which descend from this template need a disclaimer that it's based on this template.

**Comment by Mic92** [comment]
Yes. I don't consider this a problem. They can still switch to a different license if they want to.
