### ISSUE TITLE
Consider unforking from fgaz/nur-packages-template

### ISSUE THREAD

**Issue by bhipple** [nix-community/nur-packages-template#15]
The nix-community repo being a fork leads to some confusion about whether it's the "official" place to submit issues, pull requests, etc.  In general other things in `nix-community` are not forks from where they were originally located, but instead are just regular repos.

Is it sensible to unfork this?

**Comment by fgaz** [comment]
I'm not even sure that's possible though

**Comment by bhipple** [comment]
Possibly?  https://help.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by Mic92** [comment]
Can you transfer a repository while a fork already exists?

**Comment by fgaz** [comment]
Wouldn't that make us lose issues and prs?

**Comment by zimbatm** [comment]
What happens to repos who have used this repository as a template? Is there any relationship recorded?

We could rename this repo to `nur-packages-template-old` and archive it to keep the history of it before moving the other repo back to the same name.

**Comment by Mic92** [comment]
> Wouldn't that make us lose issues and prs?

Yes.

**Comment by fgaz** [comment]
> what maybe works is if you delete your repo?

...or it could also trigger a deletion of this repo :-/

I have no idea how it works internally.

Maybe we could test it out with a temporary repo, because I also want to get rid of my copy

**Comment by fgaz** [comment]
Oh wait, what if I just push a commit that puts a big redirect on the README of my copy and just archive the repo? Would that be clear enough?

**Comment by Mic92** [comment]
> > what maybe works is if you delete your repo?
> 
> ...or it could also trigger a deletion of this repo :-/
> 
> I have no idea how it works internally.
> 
> Maybe we could test it out with a temporary repo, because I also want to get rid of my copy

Sure. Just create a repo and I will fork it to nix-community.

**Comment by Mic92** [comment]
> Oh wait, what if I just push a commit that puts a big redirect on the README of my copy and just archive the repo? Would that be clear enough?

The issue is also that it tries to open pull request against your version instead of this fork. This happened to me a few times.

**Comment by fgaz** [comment]
the github fork+pr model is so broken :-/

> The issue is also that it tries to open pull request against your version instead of this fork

This does not happen with archived repos, _I think_.

> Sure. Just create a repo and I will fork it to nix-community.

https://github.com/fgaz/test-fork-behaviour

**Comment by Mic92** [comment]
@fgaz there you go https://github.com/nix-community/test-fork-behaviour

**Comment by fgaz** [comment]
Looks like the fork becomes a normal repository!

**Comment by fgaz** [comment]
> The issue is also that it tries to open pull request against your version instead of this fork. This happened to me a few times.

Aaand it happened again :joy: 

Sorry, you probably assumed I deleted it already, but I had to postpone the deletion by a few hours (I was in a rush, and deleting stuff in a rush is never good... from... experience...).

It's gone now
