### ISSUE TITLE
Migrate from Travis to Github Actions

### ISSUE THREAD

**Issue by bhipple** [nix-community/nur-packages-template#16]
Github Actions is built in by default to Github and generally has lower setup barrier than Travis.  We've recently moved NixOps and nixpkgs-update over to it and it's generally quite nice.  It might be worth considering for this repo as well.

**Comment by fgaz** [comment]
We could also include multiple CI configs (github actions, travis, builds.sr.ht, gitlab...) and let the user choose

**Comment by Mic92** [comment]
No objections if someone maintains it.

**Comment by Mic92** [comment]
I have in my repository now this github action: https://github.com/Mic92/nur-packages/blob/master/.github/workflows/build.yml

It is simpler than our current travis template.

**Comment by Mic92** [comment]
cc @domenkozar

**Comment by domenkozar** [comment]
Looks good - I plan to redo the action to fix the current two annoying issues in a couple of days :)

**Comment by Mic92** [comment]
This is my attempt: https://github.com/nix-community/nur-packages-template/pull/20

**Comment by mweinelt** [comment]
GitHub Actions would be appreciated since I have some packages that trigger the time limit on Travis CI.

**Comment by Mic92** [comment]
We have both now. Travis support is also about to be revamped leaving users to choice which to pick.
