### ISSUE TITLE
Strict eval test in build job

### ISSUE THREAD

**Issue by kolloch** [nix-community/nur-packages-template#18]
Currently, the travis build job does not do the same checks as the NUR mother repository. That means that the CI job can pass for the the user repo and the integration in NUR will still fail.

One of these things are restricting builtin fetchers: https://github.com/nix-community/NUR/issues/219

It would be nice if we made that fail in the user repo as well.

**Comment by Mic92** [comment]
agreed.

**Comment by mweinelt** [comment]
Also checking meta would be helpful here.

**Comment by Mic92** [comment]
https://github.com/nix-community/nur-packages-template/commit/295e1fa74577ccf2309cfae493f8bc0138278e55
