### ISSUE TITLE
Travis: cachix use fails (user permission for binary cache configure)

### ISSUE THREAD

**Issue by drewrisinger** [nix-community/nur-packages-template#21]
## Summary
Having issues with my cron job for ``nur-packages``. Looks like the ``cachix use`` command is failing. 

## Build Log
Relevant section of [full build log](https://travis-ci.org/github/drewrisinger/nur-packages/jobs/702179453):

```bash
$ if [ -n "${CACHIX_CACHE}" ]; then cachix use "${CACHIX_CACHE}"; fi
This user doesn't have permissions to configure binary caches.
You can either:
a) Run the same command as root to configure them globally.
b) Run the following command to add your user as trusted 
   and then try again:
  echo "trusted-users = root travis" | sudo tee -a /etc/nix/nix.conf && sudo pkill nix-daemon
The command "if [ -n "${CACHIX_CACHE}" ]; then cachix use "${CACHIX_CACHE}"; fi" failed and exited with 1 during .
```
Looks like this just started showing up in my cron history yesterday (2020-06-24). Not sure if this is a nix difference or if cachix has changed somehow. If we need to do the suggested command ``(b)``, then ``nur-packages-template`` should be updated accordingly.

### Context
I double-checked my [``.travis.yml`` file](https://github.com/drewrisinger/nur-packages/blob/master/.travis.yml), and it's practically identical to the one on ``nur-packages-template``, minus a difference in a NixOS channel.

**Comment by drewrisinger** [comment]
cc @domenkozar for cachix expertise.

**Comment by Mic92** [comment]
travis switched to nix multi-user. Since that the nix builder is no longer a trusted user, which broke cachix.

**Comment by Mic92** [comment]
The proper fix would be to do this upstream though.

**Comment by drewrisinger** [comment]
Thanks!
