### ISSUE TITLE
nix-channel --update possibly has no effect on travis

### ISSUE THREAD

**Issue by pschuprikov** [nix-community/nur-packages-template#23]
I've noticed that doing `nix-channel --update` does not have any effect on the subsequent build steps, i.e. `nixpkgs` continues to point to the version set up by `nix-install`. After failing to reproduce the behavior locally I've checked `NIX_PATH` on Travis (the [build](https://travis-ci.com/github/pschuprikov/nur-packages/jobs/365002209)) and, indeed, it did not have user channel in the list:

```bash
$ echo $NIX_PATH
nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixpkgs:/nix/var/nix/profiles/per-user/root/channels
```

I do have some minor differences compared to the template in the [.travis.yml](https://github.com/pschuprikov/nur-packages/blob/ba37acb421c5723a6594be89164d58c8b42446b1/.travis.yml), but they don't seem relevant to me.

**Comment by Mic92** [comment]
This might be a breakage when travis changed to a multi-user install.

**Comment by Mic92** [comment]
Fixed in https://github.com/nix-community/nur-packages-template/pull/25
