### ISSUE TITLE
Builds get triggered twice for pull requests

### ISSUE THREAD

**Issue by vroad** [nix-community/nur-packages-template#44]
https://github.com/nix-community/nur-packages-template/blob/c5ecbf495477b4bb41e0ea9e1ca7f0863662a900/.github/workflows/build.yml#L3

This line is unnecessary and should be removed, because workflow is already configured to trigger on every push, including pull request ones.

**Comment by Mic92** [comment]
How about that?

```
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
```

This way one can still get pull requests tested.

**Comment by vroad** [comment]
@Mic92 that's better, could you modify the template?
