### ISSUE TITLE
How to merge upstream fixes?

### ISSUE THREAD

**Issue by YellowOnion** [nix-community/nur-packages-template#59]
I'm no longer getting auto-pull requests from the bot, how can I merge changes that have been recently made?

**Comment by YellowOnion** [comment]
Yeah dependabot, It opened a PR for me once, which was rather nice.

I get:
```
$ git merge upstream 
merge: upstream - not something we can merge
```

Perhaps this is why dependabot isn't working...

**Comment by Mic92** [comment]
should not really matter for dependabot if you can merge from the template or not.

**Comment by Mic92** [comment]
I think you might have to re-enable dependabot because you use a fork.

**Comment by YellowOnion** [comment]
Na I used this template, seems to have opened PRs for the last few improvements, perhaps just an intermittent blip.
