### ISSUE TITLE
Should the original license be kept when using this as a template?

### ISSUE THREAD

**Issue by Samuel-Martineau** [nix-community/nur-packages-template#79]
This template currently has an MIT license under @fgaz's name. What is the recommendation when using this as a source for one's own NUR packages? Should the license be copied in the original files (`ci.nix`, `.github/workflows/build.yml`, etc.) or should it simply be replaced?

**Comment by Mic92** [comment]
Currently nix expressions are licensed under MIT. You agreed to this license here: https://github.com/nix-community/NUR/pull/631#issue-1999475127
